### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by gustavo-hsm** [gustavo-hsm/PoE_TradeLedger#2]
Some items collected using the Exchange API seem to cause the following error:
---
Exception in thread Thread-113:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/poetl/src/data_sink/TimedExchangeParser.py", line 17, in parse
    super().parse(response_object)
  File "/opt/poetl/src/data_sink/ExchangeParser.py", line 52, in parse
    'price']['currency']
TypeError: 'NoneType' object is not subscriptable

**Comment by gustavo-hsm** [comment]
Issue is similar to what happened in #1
