### ISSUE TITLE
TypeError: _log() got an unexpected keyword argument 'flush'

### ISSUE THREAD

**Issue by gustavo-hsm** [gustavo-hsm/PoE_TradeLedger#3]
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/poetl/src/data_channel/RequestHandler.py", line 110, in require
    self.publish()
  File "/opt/poetl/src/data_channel/RequestHandler.py", line 48, in publish
    super().publish(args)
  File "/opt/poetl/src/objects/Observer.py", line 7, in publish
    sub.update(args)
  File "/opt/poetl/src/data_channel/ExchangeManager.py", line 80, in update
    (publisher, response_object), flush=True)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1956, in error
    root.error(msg, *args, **kwargs)
  File "/usr/lib64/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'flush'

**Comment by gustavo-hsm** [comment]
Leftover argument caused this issue. The function was "print" before being updated to "logging".

**Comment by gustavo-hsm** [comment]
Should be fixed now
