### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by gustavo-hsm** [gustavo-hsm/PoE_TradeLedger#5]
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/PoE_TradeLedger-master/src/data_channel/RequestHandler.py", line 110, in require
    raise StatusCodeException(self.get_response())
  File "/home/ec2-user/PoE_TradeLedger-master/src/data_channel/ErrorHandler.py", line 77, in __init__
    self.response_text = json.loads(response_object.text)
  File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by gustavo-hsm** [comment]
Occurred after receiving a HTTP 405. "response object" was probably empty or unexpectedly malformed, which caused this error.
